export { api, getApiError, getApiFieldErrors, TOKEN_KEY } from './client';
export type { ApiResponse } from './client';
export { authApi, getOtpError } from './auth';
export type { RegisterPayload, AuthSession, LoginPortal, OtpErrorCode, OtpFailure, TermsAcceptance } from './auth';
export { profileApi } from './profile';
export type { ProfileUpdatePayload, KycSubmitPayload } from './profile';
export { supportApi, staffSupportApi, staffKycApi } from './support';
export type { CreateTicketPayload, StaffTicketCounts } from './support';
export { opsApi } from './ops';
export { tasksApi } from './tasks';
export { walletApi } from './wallet';
export { businessApi } from './business';
export { adminApi } from './admin';
export { emailApi } from './email';
export type { EmailProvider, EmailProviderInput, EmailTemplate, EmailTemplateInput, EmailLog, EmailDriver, EmailStatus, EmailCampaign, EmailCampaignInput, CampaignAudience } from './email';
export { socialChannelsApi, staffSocialChannelsApi } from './socialChannels';
export type { SocialChannel, SocialPlatform, SocialChannelStatus } from './socialChannels';
export { authProvidersApi } from './authProviders';
export type { AuthProvidersPublic, AuthProvidersAdmin, AuthProvidersInput } from './authProviders';
export { depositsApi, staffDepositsApi, formatUsd } from './deposits';
export type { DepositMethod, DepositMethodKey, DepositRequest, DepositStatus, WalletTxn, BusinessDepositsOverview } from './deposits';
