export { api, getApiError, TOKEN_KEY } from './client';
export type { ApiResponse } from './client';
export { authApi, getOtpError } from './auth';
export type { RegisterPayload, AuthSession, LoginPortal, OtpErrorCode, OtpFailure } from './auth';
export { profileApi } from './profile';
export { tasksApi } from './tasks';
export { walletApi } from './wallet';
export { businessApi } from './business';
export { adminApi } from './admin';
export { emailApi } from './email';
export type { EmailProvider, EmailProviderInput, EmailTemplate, EmailTemplateInput, EmailLog, EmailDriver } from './email';
